# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 04:53
from __future__ import unicode_literals

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_samplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=120, null=True),
        ),
    ]
