# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_restaurantlocation_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
