# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_restaurantlocation_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='docfile',
            field=models.FileField(null=True, upload_to='documents/<django.db.models.fields.CharField>/'),
        ),
    ]
