# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_auto_20171117_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
