# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_auto_20171117_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='docfile',
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/photos/'),
        ),
    ]
