# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_auto_20171117_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
