# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_auto_20171117_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_image', models.ImageField(upload_to='static/media/', verbose_name='multi_image')),
                ('restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurants.RestaurantLocation')),
            ],
        ),
    ]
