# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='restaurant',
        ),
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
