# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_auto_20171120_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/media/')),
                ('caption', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='photo',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.RestaurantLocation'),
        ),
    ]
