# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0035_photo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='照片說明'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='static/media/', verbose_name='上傳照片'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='照片標題'),
        ),
    ]
