# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0037_auto_20171121_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='restaurant',
            field=models.ForeignKey(default=restaurants.models.RestaurantLocation.get_id, on_delete=django.db.models.deletion.CASCADE, to='restaurants.RestaurantLocation'),
        ),
    ]
