# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0038_auto_20171121_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='restaurant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='restaurants.RestaurantLocation'),
        ),
    ]
