# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0041_auto_20171126_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='照片標題')),
                ('image', models.ImageField(upload_to='static/media/', verbose_name='上傳照片')),
                ('caption', models.CharField(blank=True, default='', max_length=250, verbose_name='照片說明')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.RestaurantLocation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
